### PR TITLE
cmd/zstdseek: add progress bar

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
This is a rebase of the:
* https://github.com/SaveTheRbtz/zstd-seekable-format-go/pull/123

With the following changes:
* now that we've split modules for `cmd` and `pkg` (library) we can add this code. otherwise it would be quite weird if a compression library depends on the progressbar library
* automatically show progressbar if input is a terminal.
* minor code cleanup
* minor logging cleanup

closes:
* https://github.com/SaveTheRbtz/zstd-seekable-format-go/issues/121

### CODE REVIEW

**Comment by SaveTheRbtz** [comment]
@jtarchie it took me half a year, but here it is.

Needed to re-create this one due to excessive rebases and lack of permissions on your fork.

**Comment by jtarchie** [comment]
Give me a moment, I'll download and try it out on my project.

**Comment by jtarchie** [comment]
1. Confirmed that the refactor still works with my code.
2. Confirmed that the progress bar shows up and works correctly with a large file.

**Comment by SaveTheRbtz** [comment]
Thank you for your contribution

**Pull request merged**
